### ISSUE TITLE
Add django-cas-ng 3.6+ compatibility

### ISSUE THREAD

**Issue by meg-codes** [Princeton-CDH/django-pucas#4]
django-cas-ng 3.6+ replaces its `login, logout, callback` with class-based views. This breaks the functionality of https://github.com/Princeton-CDH/django-pucas/blob/master/pucas/cas_urls.py .

To add support for future releases of django-cas-ng, we will need a release that adjusts pucas to add the class based equivalents of these three django-cas-ng routes.

**Comment by rlskoeser** [comment]
Resolved in v0.6
